client: item.o list.o playlist.o client.o
	gcc item.o list.o playlist.o client.o -o client
item.o: item.c
	gcc -c item.c
list.o: list.c
	gcc -c list.c
playlist.o: playlist.c
	gcc -c playlist.c
client.o: client.c
	gcc -c client.c
