client: item.o list.o libretto.o client.o
	gcc item.o list.o libretto.o client.o -o client
item.o: item.c
	gcc -c item.c
list.o: list.c
	gcc -c list.c
libretto.o: libretto.c
	gcc -c libretto.c
client.o: client.c
	gcc -c client.c
